# Generated by Django 3.2.3 on 2021-05-19 16:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common_files', '__first__'),
        ('children', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BBBServerDjango',
            fields=[
                ('bbbserver_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='common_files.bbbserver')),
            ],
            bases=('common_files.bbbserver',),
        ),
        migrations.CreateModel(
            name='MeetingDjango',
            fields=[
                ('meeting_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='common_files.meeting')),
            ],
            bases=('common_files.meeting',),
        ),
        migrations.RemoveField(
            model_name='meeting',
            name='server',
        ),
        migrations.DeleteModel(
            name='BBBServer',
        ),
        migrations.DeleteModel(
            name='Meeting',
        ),
    ]
