# Generated by Django 3.2.3 on 2021-06-03 18:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BBBServer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('server_id', models.IntegerField(unique=True)),
                ('url', models.CharField(default='', max_length=255)),
                ('secret', models.CharField(default='', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meeting_id', models.CharField(default='', max_length=255)),
                ('internal_id', models.CharField(default='', max_length=255)),
                ('ended', models.BooleanField(default=False)),
                ('load', models.IntegerField()),
                ('create_query', models.JSONField(default=dict)),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common_files.bbbserver')),
            ],
        ),
    ]
