# Generated by Django 3.2.3 on 2021-06-03 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common_files', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bbbserver',
            name='reachable',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='bbbserver',
            name='state',
            field=models.CharField(choices=[('ENABLED', 'enabled'), ('DISABLED', 'disabled'), ('PANIC', 'panic')], default='ENABLED', max_length=255),
        ),
    ]
