# Generated by Django 3.2.4 on 2021-06-13 17:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common_files', '0002_auto_20210603_1936'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='moved_to',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='common_files.meeting'),
        ),
    ]
