# Generated by Django 3.2.3 on 2021-06-03 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common_files', '0003_meeting_load'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='create_query',
            field=models.JSONField(default=dict),
        ),
    ]
