# Generated by Django 3.2.3 on 2021-06-03 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common_files', '0004_meeting_create_query'),
    ]

    operations = [
        migrations.AddField(
            model_name='bbbserver',
            name='server_id',
            field=models.IntegerField(default=0, unique=True),
            preserve_default=False,
        ),
    ]
