# Generated by Django 3.2.4 on 2021-06-24 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common_files', '0004_meeting_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
